name: .NET CI Pipeline

on:
  push:
    branches:
      - main
      - master
      - develop
  pull_request:
    branches:
      - '**'

jobs:
  build-test:
    name: Build, Test, and Publish Artifacts
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout source code
        uses: actions/checkout@v4

      # Step 2: Setup .NET SDK
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      # Step 3: Restore dependencies
      - name: Restore dependencies
        run: dotnet restore *.sln

      # Step 4: Build solution
      - name: Build
        run: dotnet build *.sln --configuration Release --no-restore

      # Step 5: Run tests
      - name: Run tests
        run: dotnet test *.sln --configuration Release --no-build --logger "trx;LogFileName=test_results.trx" --results-directory ./TestResults

      # Step 6: Upload test results as artifact
      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: ./TestResults/*.trx

      # Step 7: Publish build artifacts
      - name: Publish build output
        run: dotnet publish *.sln --configuration Release --output ./publish --no-build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: ./publish